# 站点设置
title: Yihuier
description: Hello, I'm Yihuier.
url: https://yihuier.github.io
baseurl: ""
author: Yihuier

# 构建设置
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 导航链接
navigation:
  - title: 首页
    url: /
  - title: 博客
    url: /blog/

# 社交媒体链接
social:
  github: https://github.com/yihuier 